export enum ListConstants {
  ADD_ITEM = "ADD_ITEM",
  GET_LIST_ITEMS_START = "GET_LIST_ITEMS_START",
  GET_LIST_ITEMS_SUCCESS = "GET_LIST_ITEMS_SUCCESS",
  GET_LIST_ITEMS_FAIL = "GET_LIST_ITEMS_FAIL",
  GET_ITEM_START = "GET_ITEM_START",
  GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS",
  GET_ITEM_FAIL = "GET_ITEM_FAIL",
}
